<?php
// FILE: includes/changelog-data.php

$entries = [
    [
        'date'    => 'April 18, 2026',
        'version' => 'v4.1 — Project Management & SEO Architecture',
        'changes' => [
            ['type' => 'new',    'note' => 'Project Management Module: Launched the comprehensive administrative suite for creating and curating cinematic project narratives, gallery albums, and unit inventories.'],
            ['type' => 'new',    'note' => 'Dashboard Telemetry: Integrated a real-time platform version indicator linked directly to the central release registry for administrative transparency.'],
            ['type' => 'new',    'note' => 'Cascading Sanitation Engine: Engineered a secure lead-purge module that automatically cleanses associated tasks, deals, and document assets during deletion.'],
            ['type' => 'new',    'note' => 'Cinematic Map Explorer: Launched a streamlined, high-performance project map interface with autonomous location pinning and regional query locking.'],
            ['type' => 'update', 'note' => 'Navigation Restoration: Decoupled direct website inquiries from the general CRM archive in the sidebar for specialized response tracking.'],
            ['type' => 'update', 'note' => 'Dynamic Navigation Engine: Implemented a self-populating project sub-menu in the global header that automatically updates with new development entries.'],
            ['type' => 'fix',    'note' => 'Initialization Sequence: Resolved a critical "Undefined Variable $pdo" failure by re-ordering the header database connection logic.'],
            ['type' => 'new',    'note' => 'SEO Clean Routing: Engineered advanced .htaccess rewrites for vanity project URLs (e.g., /projects/slug), optimizing search visibility and brand perception.'],
            ['type' => 'update', 'note' => 'Contact Compatibility: Enhanced WhatsApp communication bridges with the international "+" prefix protocol for seamless global lead routing.'],
            ['type' => 'update', 'note' => 'Atmospheric Map Styling: Refined the geography section into a stable, non-blocking immersive card design with zero-filter rendering for local stability.'],
            ['type' => 'fix',    'note' => 'Self-Healing Database: Deployed a real-time schema persistence layer that autonomously provisions missing contact columns (agent_phone/whatsapp) during save operations.'],
            ['type' => 'fix',    'note' => 'Structural Tag Integrity: Resolved critical rendering breaks and unclosed iframe failures that caused layout shifts in the Location Strategy module.'],
        ],
    ],
    [
        'date'    => 'April 17, 2026',
        'version' => 'v4.0 — CRM Operational Infrastructure',
        'changes' => [
            ['type' => 'new',    'note' => 'CRM Lead Management (360° Profile): Interactive Timeline tracking calls, emails, meetings, and internal notes.'],
            ['type' => 'new',    'note' => 'Log Activity Module: High-fidelity modal for real-time interaction recording with lead-specific metadata.'],
            ['type' => 'new',    'note' => 'Lead Performance Editor: Direct interface for updating contact details, property interests, and investment preferences.'],
            ['type' => 'update', 'note' => 'Layout Ergonomics: Redesigned the "Add Lead" form into a 2-column wide grid for optimized data induction.'],
            ['type' => 'new',    'note' => 'Sales Pipeline & Kanban: Deployed a drag-and-drop board for visual deal tracking across custom stages.'],
            ['type' => 'new',    'note' => 'Quick Deal Induction: Integrated searchable contact/property pickers for high-speed deal expansion.'],
            ['type' => 'new',    'note' => 'Centralized Identity Directory: Created master registry for Buyers, Sellers, Investors, and Tenants.'],
            ['type' => 'update', 'note' => 'Persona Intelligence: Expanded support for the Tenant persona with specialized interest workflows.'],
            ['type' => 'update', 'note' => 'Discovery Accessibility: Made View, Download, and Delete actions permanently visible in Document and Task centers.'],
            ['type' => 'fix',    'note' => 'Architectural Path Fix: Resolved 404 errors by implementing root-relative asset mapping for all archived documents.'],
            ['type' => 'new',    'note' => 'Operational Habit Tracker: Functionalized the Daily Tasks module with intelligent lead-linkage.'],
            ['type' => 'update', 'note' => 'Priority Matrix: Integrated visual urgency indicators and overdue alerts for precision time management.'],
            ['type' => 'update', 'note' => 'Aesthetic Refinement (Gallery): Updated cinematic title architecture for the Gallery showcase page.'],
            ['type' => 'update', 'note' => 'Identity Navigation: Refined the "My Profile" section within the global header menu for improved persona access.'],
        ],
    ],
    [
        'date'    => 'April 16, 2026',
        'version' => 'v3.5 — Performance Engine & Curation Stability',
        'changes' => [
            ['type' => 'new',    'note' => 'Server-Side Caching: Launched a robust file-based caching engine with configurable TTL to deliver near-instant load times for property listings and details.'],
            ['type' => 'new',    'note' => 'Atomic Invalidation: Engineered a "Freshness First" protocol that automatically purges relevant cache snapshots during content updates or deletions.'],
            ['type' => 'new',    'note' => 'Cache Management Dashboard: Created a dedicated administrative control center for monitoring cache health, storage metrics, and manual system purges.'],
            ['type' => 'update', 'note' => 'Premium Upload Redesign: Re-engineered the image upload experience with a cinematic modal featuring 10-dot segmented progress tracking and micro-animations.'],
            ['type' => 'update', 'note' => 'Sequential Batch Logic: Optimized concurrent uploads with a sequential processing queue, ensuring stability and real-time feedback for bulk asset management.'],
            ['type' => 'fix',    'note' => 'Rich Text Integrity: Resolved a rendering bug that caused raw HTML tags to appear in property descriptions, restoring full cinematic content formatting.'],
            ['type' => 'fix',    'note' => 'Layout Logic Stability: Fixed structural failures in the administrative portal by synchronizing missing HTML boilerplate and footer partials.'],
        ],
    ],
    [
        'date'    => 'March 30, 2026',
        'version' => 'v3.4 — Cinematic Identity & Architectural Navigation',
        'changes' => [
            ['type' => 'new',    'note' => 'Homepage Hero Appearance: Launched a dedicated administration suite for managing the site\'s primary cinematic background with real-time previews and upload support.'],
            ['type' => 'update', 'note' => 'Premium Navigation 2.0: Implemented a sophisticated split-identity navigation bar. The homepage features a minimalist "Ice-White" frame, while inner pages adopt a robust branded accent outline for structural clarity.'],
            ['type' => 'new',    'note' => 'Centralized Identity Engine: Unified the site-wide brand accent (#899178) across all core CSS and PHP logic, ensuring perfect color consistency across the entire ecosystem.'],
            ['type' => 'update', 'note' => 'Navigational Clarity: Re-architected the central menu to include "Gallery", "Stories", and "Contact Us", while refining Properties into an intuitive Residential/Commercial dropdown.'],
            ['type' => 'new',    'note' => 'High-Definition Upload Suite: Expanded server infrastructure via .htaccess overrides to support 20MB cinematic asset uploads, paired with a new server-health diagnostic dashboard.'],
            ['type' => 'fix',    'note' => 'Filter Layering Stability: Resolved a z-index collision between the redesigned Properties Filter bar and the new absolute-positioned global navigation.'],
            ['type' => 'new',    'note' => 'Global Accent Injection: Developed a dynamic :root variable system in header.php, allowing the glassmorphism navigation to adapt instantly to database-stored brand colors.'],
        ],
    ],
    [
        'date'    => 'March 28, 2026',
        'version' => 'v3.3 — AI Chat Redesign & Intelligence Refinement',
        'changes' => [
            ['type' => 'new',    'note' => 'Launcher Bubble Redesign: Transitioned the AI launcher to a modern pill-shaped button featuring the Apple Intelligence mark and "Ask Advet" branding, optimized for premium tactile feedback.'],
            ['type' => 'new',    'note' => 'Custom Clear Chat Modal: Replaced standard browser dialogs with a bespoke, themed confirmation modal for a cohesive and professional history management experience.'],
            ['type' => 'update', 'note' => 'Bot Identity & SVG Refinement: Implemented a high-fidelity "floating" twotone SVG identity for Advet AI, removing background containers for a lighter, more modern chat persona.'],
            ['type' => 'fix',    'note' => 'Session Persistence Bug: Resolved a critical issue where new chats would merge with old history after page navigation by implementing a synchronized backend/frontend session clear.'],
            ['type' => 'new',    'note' => 'Quick-Prompt Chips: Added contextual suggestion pills ("Available properties", "Price ranges", "Schedule visit") above the input field that auto-dismiss after first use.'],
            ['type' => 'new',    'note' => '1-Hour Chat History TTL: Implemented an automatic purge system that deletes all chat messages from inactive sessions older than 1 hour.'],
            ['type' => 'update', 'note' => 'Chat Window Animation: Integrated spring-eased scale + fade transitions for a more organic and responsive interaction feel.'],
        ],
    ],
    [
        'date'    => 'March 27, 2026',
        'version' => 'v3.2 — Studio Stability & Asset Integrity',
        'changes' => [
            ['type' => 'update', 'note' => 'Commercial Transition: Rebranded the "Spaces" module to a dedicated "Commercial" portfolio, including route migrations and specialized navigation integration.'],
            ['type' => 'fix',    'note' => 'Commercial Link Integrity: Resolved a critical data-binding bug where Commercial listings were missing slugs, preventing detail page redirects.'],
            ['type' => 'update', 'note' => 'AI Chat Intelligence: Enhanced "ASK Advet" with RAG-lite location awareness and automated, clickable property linking in Markdown format.'],
            ['type' => 'update', 'note' => 'AI Connection Resilience: Implemented a PDO health-check and IPv4-first resolution to prevent "MySQL server has gone away" errors and improve response speeds.'],
            ['type' => 'update', 'note' => 'Chat Persistence Suite: Integrated LocalStorage-backed state management, allowing the AI chat window and history to persist across page refreshes and navigation.'],
            ['type' => 'fix',    'note' => 'Stories Visibility: Corrected a loop logic bug on the Stories page that was inadvertently hiding every third blog post.'],
            ['type' => 'fix',    'note' => 'Asset Resolution: Resolved broken gallery images on property detail pages by implementing a global path-mapping helper.'],
            ['type' => 'fix',    'note' => 'Duplicate Prevention: Engineered a state-aware upload handler that ignores redundant multi-part file submissions when asynchronous paths are present.'],
            ['type' => 'fix',    'note' => 'Cross-Platform Removal: Implemented slash-agnostic path comparison for image removal, ensuring full compatibility with Windows/WAMP server file systems.'],
            ['type' => 'update', 'note' => 'Uploader Sync: Linked UI preview removal (X button) directly to form submission state, preventing unwanted image saves after removal from the curation grid.'],
            ['type' => 'update', 'note' => 'System Guard: Added a singleton-pattern guard to the uploader component to prevent duplicate listener attachment during dynamic DOM mutations.'],
        ],
    ],
    [
        'date'    => 'March 26, 2026',
        'version' => 'v3.1 — Studio Integrity & Experience Refinement',
        'changes' => [
            ['type' => 'new',    'note' => 'Segmented Dot Uploader: Launched a new high-end image upload component featuring dynamic dot progress indicators and a "Curation Portal" aesthetic across all modules.'],
            ['type' => 'new',    'note' => 'Mini Mode Integration: Engineered specialized uploader variants for circular profile avatars and real-time image replacement for instant visual feedback.'],
            ['type' => 'fix',    'note' => 'Interface Integrity: Resolved vertical stacking, circular clipping, and flex-box collisions between legacy zones and the new global uploader.'],
            ['type' => 'update', 'note' => 'Team Profile Suite: Optimized real-time previews and storage handlers for team members, ensuring architectural consistency during curation.'],
            ['type' => 'update', 'note' => 'Responsiveness Suite: Optimized the uploader\'s spatial awareness for narrow columns and mobile environments across all Studio modules.'],
        ],
    ],
    [
        'date'    => 'March 25, 2026',
        'version' => 'v3.0 — Core Expansion & Content Engagement',
        'changes' => [
            ['type' => 'new',    'note' => 'AI Chat Integration: Launched "ASK Advet" - an intelligent real-estate advisory assistant for seamless property inquiries.'],
            ['type' => 'new',    'note' => 'Journal SEO Suite: Individual meta title, description, and keyword controls for every story to maximize search visibility.'],
            ['type' => 'new',    'note' => 'Comment & Response System: Integrated a fully functional engagement engine for stories, allowing readers to share insights directly on the journal.'],
            ['type' => 'new',    'note' => 'Story Moderation Panel: Launched a dedicated admin center to approve, delete, or mark comments as spam, ensuring high-quality site interactions.'],
            ['type' => 'update', 'note' => 'Pending Alert Badges: Added real-time notification dots in the All Stories list to signal new responses awaiting administrative review.'],
            ['type' => 'new',    'note' => 'Gallery & Album System: Launched a comprehensive photo management engine. Admins can create albums, bulk-upload photos, and select featured covers.'],
            ['type' => 'new',    'note' => 'FAQ Management: Integrated a fully manageable FAQ system from the dashboard with modern public accordion interface.'],
            ['type' => 'update', 'note' => 'Sidebar Categorization: Re-engineered admin navigation into logical industry-standard groups (Real Estate, CRM, Content, System).'],
        ],
    ],
    [
        'date'    => 'March 18, 2026',
        'version' => 'v2.5 — Profile System, Role Access Control & System Health',
        'changes' => [
            ['type' => 'new',    'note' => 'Live System Health Metrics: Dashboard now displays real-time data — DB ping latency (ms), live disk free space (GB), and live PHP memory usage against server limit, replacing all static placeholder values.'],
            ['type' => 'new',    'note' => 'Profile Picture System: All users (admin, agent, member) can upload a personal avatar from their profile page. Images securely stored in assets/uploads/users/ with 2MB size and format validation.'],
            ['type' => 'new',    'note' => 'Admin Profile Page: Created admin/profile.php — a dedicated settings panel for admins and agents to update their name, email, password, and avatar in one unified interface.'],
            ['type' => 'new',    'note' => 'Member Portal Profile: Normal registered members are directed to public/profile.php to manage their account details.'],
            ['type' => 'new',    'note' => 'uploadProfilePicture() Helper: Added a reusable, secure image upload utility to config/db.php specifically for user avatar handling.'],
            ['type' => 'update', 'note' => 'Role-Based Admin Sidebar: Sidebar navigation is now fully role-gated. Admins and agents see Overview, Listings, Inquiries, and Admin Control sections. Normal members see only My Profile.'],
            ['type' => 'update', 'note' => 'Role-Based Header Menu: Desktop dropdown and mobile tray now adapt per role. Admins/agents see Dashboard + My Profile + Logout. Normal members see only My Account button with My Profile + Logout (Dashboard hidden).'],
            ['type' => 'update', 'note' => 'Sidebar Avatar Widget: The bottom user widget in the admin sidebar now renders the user\'s profile picture as a round avatar (or initials fallback). Clicking it links directly to the profile page.'],
            ['type' => 'update', 'note' => 'Session Hydration: Login handler updated to SELECT * from users, ensuring newly added columns (profile_picture) are automatically included in the session without manual updates.'],
            ['type' => 'fix',    'note' => 'Member Dashboard Redirect: Members trying to access admin/dashboard.php are now redirected to the homepage instead of the login page, since they are already authenticated.'],
            ['type' => 'fix',    'note' => 'All 21 admin pages updated: Auth guards split — unauthenticated users go to login, wrong-role users (members on agent pages, non-admins on admin pages) are gracefully redirected to the homepage.'],
            ['type' => 'fix',    'note' => 'Profile Cancel Button: The Cancel button on the profile page is role-aware — members return to homepage, admins/agents return to the dashboard.'],
            ['type' => 'fix',    'note' => 'My Profile Link Routes: My Profile link in the header dropdown now correctly routes — members go to public/profile.php (Member Portal), staff go to admin/profile.php (Admin Panel).'],
            ['type' => 'update', 'note' => 'Contact Us Button Style: Updated the header Contact Us button (desktop) and Get in Touch button (mobile) to use brand olive color #899178 with off-white #FDFCF9 text for consistency with the design system.'],
        ],
    ],
    [
        'date' =>'March 18, 2026',
        'version' => 'v2.4 — Floating Glass Pill & Narrative Evolution',
        'changes' => [
            ['type' => 'new', 'note' => 'Floating Glass Pill Navigation: Implemented a trend-setting, detached capsule header with heavy glassmorphism and subtle radiant borders.'],
            ['type' => 'new', 'note' => 'Bilingual Narrative Architecture: Introduced a sophisticated bilingual (#NayaGharNayiZindagi) hero section for localized resonance.'],
            ['type' => 'update', 'note' => 'Interactive Hybrid Sub-menus: Re-engineered dropdown interactions with a CSS "Hover Bridge" and high-contrast Bento-style design.'],
            ['type' => 'fix', 'note' => 'Navigation Layering Stability: Corrected viewport clipping issues (overflow-hidden) to ensure absolute-positioned dropdowns render perfectly across all devices.'],
            ['type' => 'new', 'note' => 'Personalized Profile Integration: Launched a dedicated "My Profile" space for individual user identity, accessible via the new Management ecosystem.'],
            ['type' => 'update', 'note' => 'Unified Session Management: Re-engineered the "Dashboard" administrative link into a sophisticated Bento-style sub-menu, consolidating Profile and Logout utilities for a cleaner ecosystem.'],
        ]
    ],
    [
        'date' => 'March 17, 2026',
        'version' => 'v2.3 — Branding & Identity Evolution',
        'changes' => [
            ['type' => 'new', 'note' => 'Dual Logo Architecture: Introduced separate administrative controls for visual Icon Logos and sophisticated Editable Text branding.'],
            ['type' => 'new', 'note' => 'Secure Password Recovery: Implemented a comprehensive account restoration system with encrypted tokens and premium HTML notifications.'],
            ['type' => 'new', 'note' => 'Favicon Personalization: Added support for custom site favicons (.ico, .png, .svg) with real-time browser preview in settings.'],
            ['type' => 'update', 'note' => 'Typography Optimization: Integrated the "Outfit" font family globally while maintaining "Cormorant Garamond" for heritage branding elements.'],
            ['type' => 'update', 'note' => 'Offline-First Fonts: Migrated all typography to local storage, eliminating external dependencies and improving performance.'],
            ['type' => 'new', 'note' => 'Live Migration Engine: Developed a server-side upgrade utility (upgrade.php) for safe, one-click database synchronization on live servers.'],
            ['type' => 'update', 'note' => 'Advanced Utility Routing: Refined .htaccess to support clean URL mapping for utility files located in the project root.'],
            ['type' => 'fix', 'note' => 'Branding Continuity: Synchronized serif font-face declarations to ensure consistent identity across the digital ecosystem.'],
        ]
    ],
    [
        'date' => 'March 16, 2026',
        'version' => 'v2.2 — Deployment & Routing Optimization',
        'changes' => [
            ['type' => 'fix', 'note' => 'Search & Filter Reliability: Corrected form actions and refined .htaccess routing to ensure queries like search and filters work seamlessly with Clean URLs.'],
            ['type' => 'new', 'note' => 'Advanced SEO-friendly Slug Routing: Properties and stories now feature descriptive URLs (e.g. /property/post-name) instead of IDs.'],
            ['type' => 'new', 'note' => 'Implemented Clean URLs across the entire platform, automatically stripping .php extensions and redirecting index.php to root.'],
            ['type' => 'new', 'note' => 'Implemented Dynamic BASE URL Detection for seamless environment switching between localhost and live servers.'],
            ['type' => 'update', 'note' => 'Refined .htaccess with subfolder-agnostic routing rules and robust extensionless URL support.'],
            ['type' => 'update', 'note' => 'Enhanced Web Installer (install.php) with dynamic schema loading and secure administrative setup.'],
            ['type' => 'update', 'note' => 'Migrated global social media architecture to socialvynk.space domain.'],
            ['type' => 'fix', 'note' => 'Resolved critical "Member Profile" crash by synchronizing inquiries database schema.'],
            ['type' => 'fix', 'note' => 'Fixed featured property data visualization bugs on the root homepage.'],
            ['type' => 'fix', 'note' => 'Corrected post-installation redirection paths for subdirectory deployments.'],
        ]
    ],
    [
        'date' => 'March 14, 2026',
        'version' => 'v2.1 — Studio Intelligence & Team Evolution',
        'changes' => [
            ['type' => 'new', 'note' => 'Launched comprehensive Team Management system with full administrative CRUD controls.'],
            ['type' => 'update', 'note' => 'Optimized Legal Pages administration with a streamlined, stable Rich Text interface (Quill.js) for high-performance policy management.'],
            ['type' => 'new', 'note' => 'Implemented Studio Logo upload system supporting SVG, PNG, and JPG formats.'],
            ['type' => 'new', 'note' => 'Added "Inquiry Notifications" system with automated email alerts for administrators.'],
            ['type' => 'new', 'note' => 'Integrated global Social Media management (Facebook, Instagram, YouTube, LinkedIn, Socialvynk) with refined minimalist text-based integration.'],
            ['type' => 'new', 'note' => 'Developed "Studio Presence" management for dynamic location, phone, and hours across the platform.'],
            ['type' => 'new', 'note' => 'Created dynamic "Collective" team page with a sophisticated staggered layout.'],
            ['type' => 'update', 'note' => 'Developed intelligent social media cleansing for admin inputs (auto-stripping handles/URLs).'],
            ['type' => 'update', 'note' => 'Synchronized the "Collective Advisors" section on the About page with live database.'],
            ['type' => 'update', 'note' => 'Integrated automated platform URL prefixing for all major social media links.'],
            ['type' => 'update', 'note' => 'Implemented administrative controls for "Featured Projects" (Neighborhood Spotlight).'],
            ['type' => 'update', 'note' => 'Standardized system-wide iconography with premium Hugeicons optimized for accessibility.'],
            ['type' => 'fix', 'note' => 'Corrected timeline alignment issues on the public changelog interface.'],
            ['type' => 'fix', 'note' => 'Fixed "Profile" link visibility in navigation during transparent to solid state transitions.'],
            ['type' => 'fix', 'note' => 'Resolved data synchronization issue between Studio Presence settings and the contact page interface.'],
        ]
    ],
    [
        'date' => 'March 13, 2026',
        'version' => 'v2.0 — Administrative Expansion',
        'changes' => [
            ['type' => 'new', 'note' => 'Added system status indicators and real-time performance metrics to the dashboard.'],
            ['type' => 'new', 'note' => 'Integrated Market Analytics and Studio Settings administrative modules.'],
            ['type' => 'update', 'note' => 'Enhanced inquiry management with real-time status tracking and filtering.'],
            ['type' => 'update', 'note' => 'Unified system navigation with seamless "Our Team" routing and sidebar integration.'],
            ['type' => 'fix', 'note' => 'Resolved session persistence issues in the administrative authentication layer.'],
        ]
    ],
    [
        'date' => 'March 12, 2026',
        'version' => 'v1.0 — Platform Relaunch & CMS',
        'changes' => [
            ['type' => 'new', 'note' => 'Complete migration to PHP backend with robust MySQL database architecture.'],
            ['type' => 'new', 'note' => 'Launched the "Spaces" property management engine with dynamic listing capabilities.'],
            ['type' => 'update', 'note' => 'Established site-wide minimalist design system using local Tailwind CSS.'],
            ['type' => 'update', 'note' => 'Developed the "Stories" journal system for architectural narratives.'],
            ['type' => 'fix', 'note' => 'Optimized image loading performance across high-resolution property galleries.'],
        ]
    ],
];
